#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


TOTAL_STAGES=10

ENV_FILE="$HOME/.box-setup.env"
BOARD_DIR="$HOME/.comet-native/board"

# board_env KEY VALUE — upsert into the board's own .env (not the wizard state).
board_env() {
  mkdir -p "$BOARD_DIR"; touch "$BOARD_DIR/.env"
  local tmp; tmp=$(mktemp)
  grep -vE "^$1=" "$BOARD_DIR/.env" > "$tmp" || true
  printf '%s=%s\n' "$1" "$2" >> "$tmp"
  mv "$tmp" "$BOARD_DIR/.env"; chmod 600 "$BOARD_DIR/.env"
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$1" "$BOARD_DIR/.env"
}

banner "comet box setup — run as the comet user on the box"

# ── 1 ──────────────────────────────────────────────────────────────────
stage "Rust toolchain"
if command -v cargo >/dev/null 2>&1; then
  say "cargo already present: $(cargo --version)"
else
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  . "$HOME/.cargo/env"
fi

# ── 2 ──────────────────────────────────────────────────────────────────
stage "GitHub CLI sign-in + clone"
say "gh's device flow prints a code; open the URL on your laptop."
gh auth status >/dev/null 2>&1 || gh auth login --hostname github.com --git-protocol https --web
[ -d "$HOME/comet-board" ] || gh repo clone bredebjorhovd/comet-board "$HOME/comet-board"
say "${GREEN}✓${RESET} repo at ~/comet-board"

# ── 3 ──────────────────────────────────────────────────────────────────
stage "Git identity — whose name the agents commit under"
say "A box with no \`git config user.*\` does not refuse to commit: git invents"
say "an author from the box user and hostname, the commits go up attributed to"
say "no GitHub account, and a deploy gate that checks the author (Vercel's)"
say "refuses to build the push. Pin it now, before anything dispatches."
say ""
if [ -n "$(git config --global user.email 2>/dev/null || true)" ]; then
  note "currently: $(git config --global user.name 2>/dev/null || echo '?') <$(git config --global user.email)>"
fi
# The account you just signed gh in as can answer this itself: GitHub's noreply
# address is `<id>+<login>@users.noreply.github.com`, and both halves are on the
# `/user` response. No copying from a settings page, no address to mistype.
gh_ident=$(gh api user --jq '"\(.id)+\(.login)@users.noreply.github.com"' 2>/dev/null || true)
gh_name=$(gh api user --jq '.name // .login' 2>/dev/null || true)
if [ -n "$gh_ident" ]; then
  say "from the account gh is signed in as: ${BOLD}$gh_name <$gh_ident>${RESET}"
else
  warn "gh could not answer — yours is at https://github.com/settings/emails"
  open_url "https://github.com/settings/emails"
  ask GIT_NAME "Name to commit as:"
  ask GIT_EMAIL "Email (<id>+<login>@users.noreply.github.com):"
  gh_name="$GIT_NAME"; gh_ident="$GIT_EMAIL"
fi
if [ -n "$gh_ident" ]; then
  git config --global user.name "$gh_name"
  git config --global user.email "$gh_ident"
  say "${GREEN}✓${RESET} $(git config --global user.name) <$(git config --global user.email)>"
else
  SKIPPED+=("git identity (git config --global user.email …) — agents will commit as nobody")
  warn "no identity set — \`comet-board doctor\` will keep failing until there is one"
fi
note "This is the box's own identity, and the committer on everything it runs."
note "A teammate dispatching this board authors as themselves instead — map"
note "their sign-in email in routing.toml's [users] (stage 10, docs/BOARD.md H18)."

# ── 4 ──────────────────────────────────────────────────────────────────
stage "Install comet + comet-board"
say "Preferred: the prebuilt tarball from our edge (exists once gh#54's"
say "release pipeline has tagged a version). Falls back to building from"
say "source — on a small box add swap first (4 GB is tight at link time):"
note "  sudo fallocate -l 4G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile"
if curl -fsSL --max-time 20 https://edge.comet.offhand.dev/install.sh | sh; then
  say "${GREEN}✓${RESET} installed from release tarball"
else
  warn "no release published yet — building from source (slow on 2 vCPU)"
  ( cd "$HOME/comet-board" && . "$HOME/.cargo/env" && cargo build --release -j 2 -p comet -p comet-board-bin )
  mkdir -p "$HOME/.local/bin"
  ln -sf "$HOME/comet-board/target/release/comet" "$HOME/.local/bin/comet"
  ln -sf "$HOME/comet-board/target/release/comet-board" "$HOME/.local/bin/comet-board"
fi
grep -q '.local/bin' "$HOME/.profile" 2>/dev/null || echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.profile"
export PATH="$HOME/.local/bin:$PATH"
say "${GREEN}✓${RESET} $(comet --version 2>/dev/null || echo 'comet installed')"

# ── 5 ──────────────────────────────────────────────────────────────────
stage "Claude CLI (the agents' harness)"
command -v claude >/dev/null 2>&1 || sudo npm install -g @anthropic-ai/claude-code 2>/dev/null || npm install -g @anthropic-ai/claude-code
if [ -f "$HOME/.claude/.credentials.json" ]; then
  say "claude already authenticated — skipping"
else
  say "Sign the CLI in (interactive): claude opens, type /login, pick"
  say "'Claude account with subscription', open the URL on your laptop,"
  say "paste the code back, then exit claude to continue."
  note "(setup-token is NOT enough — it mints a CI token without logging in.)"
  claude || true
  [ -f "$HOME/.claude/.credentials.json" ] && say "signed in" || warn "still not signed in — rerun this stage"
fi

# ── 6 ──────────────────────────────────────────────────────────────────
stage "comet sign-in (WorkOS paste-code)"
say "This prints a sign-in URL (open on your laptop, approve, copy the code"
say "from the hosted page, paste it back here)."
comet login
comet status | head -6
pause "Status shows Edge edge.comet.offhand.dev and your WorkOS user?"

# ── 7 ──────────────────────────────────────────────────────────────────
stage "Daemon under systemd"
comet daemon install && comet daemon status || warn "daemon install/status failed — check: journalctl --user -u comet"
say "${GREEN}✓${RESET} the engine survives reboots (linger is on)"

# ── 8 ──────────────────────────────────────────────────────────────────
stage "Linear key"
say "The board polls Linear with one API key (Linear → Settings → Security &"
say "access → Personal API keys — or a workspace key)."
open_url "https://linear.app/settings/account/security"
ask_secret LINEAR_KEY "Paste the Linear API key (lin_api_…):"
board_env LINEAR_API_KEY "$LINEAR_KEY"

# ── 9 ──────────────────────────────────────────────────────────────────
stage "GitHub App — the board's own credential"
say "One App, installed on each account whose repos the board works"
say "(bredebjorhovd + Florin-AS). Personal-owned works if set to 'Any account'."
open_url "https://github.com/settings/apps/new"
step "Name: comet-board-<you>. Homepage: the repo URL. Webhook: UNCHECK active."
step "Permissions → Repository: Contents RW · Issues RW · Pull requests RW ·"
step "  Metadata R. 'Where can it be installed' → Any account."
step "Create → note the App ID → Generate a private key (.pem downloads)."
ask GH_APP_ID "App ID (number):"
board_env GITHUB_APP_ID "$GH_APP_ID"
step "Install the App: its page → Install App → both accounts → select the"
step "  team's repos."
step "From your laptop: scp ~/Downloads/<the-key>.pem comet@<this-box>:.comet-native/board/github-app.pem"
pause "PEM copied to ~/.comet-native/board/github-app.pem?"
chmod 600 "$BOARD_DIR/github-app.pem" 2>/dev/null || warn "pem not found at $BOARD_DIR/github-app.pem yet"
board_env GITHUB_APP_PRIVATE_KEY_PATH "$BOARD_DIR/github-app.pem"

# ── 10 ─────────────────────────────────────────────────────────────────
stage "Routes, agent skill + doctor"
say "Seeding routing.toml from this device's spaces, then the truth test:"
comet-board init 2>/dev/null || note "init needs the daemon up and spaces created — fine to re-run later"
say ""
say "The board's own skill, so every Claude session on this box knows the"
say "conventions (verbs, tickets-first, billing, wait --blocked-is-settled):"
comet-board skill install || warn "skill install failed — \`comet-board doctor\` will say so"
note "Ships inside the binary, so \`comet-board skill install\` again after an"
note "upgrade. Dispatched agents run under an agent-account slot, which gets"
note "its own copy automatically — nothing to do per slot."
say ""
note "Clone the team's repos under ~/dev (or wherever), open them once so"
note "spaces exist, then: comet-board adopt <slug> — or edit"
note "$BOARD_DIR/routing.toml by hand (routes need workspace/repo/runtime)."
say ""
note "One more table worth filling in while you are in there — [users], which"
note "maps a teammate's sign-in email to their GitHub address so their"
note "dispatches commit as them rather than as this box:"
note "  [users]"
note "  \"ana@example.com\" = \"22494697+ana@users.noreply.github.com\""
note "(each person's own address is on https://github.com/settings/emails)"
say ""
comet-board doctor || warn "doctor is not green yet — it names exactly what is missing; fix and re-run it"

finish
