#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Run from anywhere; all paths resolve from the repo root. Captured values go
# to an untracked state file so re-runs remember them — never commit it.
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"
ENV_FILE="$ROOT/.edge-setup.env"

# patch FILE PERL_EXPR CHECK_PATTERN — in-place edit, then verify the result
# actually contains what we expect. Warns instead of dying so a re-run over an
# already-patched file is fine.
patch() {
  local file="$1" expr="$2" check="$3"
  perl -pi -e "$expr" "$file"
  if grep -q "$check" "$file"; then
    printf '  %s✓ patched%s %s\n' "$GREEN" "$RESET" "$file"
  else
    warn "$file does not contain expected '$check' after patching — check it by hand"
  fi
}

banner "comet-board edge setup (Cloudflare + WorkOS) — issue #51"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare sign-in + account id"
say "wrangler needs to act as your Cloudflare account, and wrangler.jsonc"
say "still pins upstream's account id."
step "A browser will open; approve wrangler's OAuth request."
( cd edge && npm ci --no-audit --no-fund >/dev/null 2>&1 || npm install --no-audit --no-fund >/dev/null )
( cd edge && npx wrangler login ) || warn "wrangler login failed — already logged in is fine"
say ""
say "Your account id (32 hex chars) is printed by whoami:"
( cd edge && npx wrangler whoami 2>/dev/null | tail -5 ) || true
ask CF_ACCOUNT_ID "Paste your Cloudflare account id:"
write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"
patch edge/wrangler.jsonc "s/b57dde68ee5964dccc025437b5478a5b/$CF_ACCOUNT_ID/" "$CF_ACCOUNT_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Edge hostname"
say "Pick any hostname under a zone already in this Cloudflare account"
say "(e.g. edge.comet.offhand.dev under the offhand.dev zone)."
say ""
say "You do NOT create the subdomain anywhere: 'custom_domain: true' on the"
say "route makes 'wrangler deploy' create the DNS record AND issue the TLS"
say "certificate for that exact hostname. Deep subdomains are fine."
note "Only conflict: if a DNS record for that exact name already exists in"
note "the zone, delete it first (dash → zone → DNS → Records)."
ask EDGE_HOSTNAME "Edge hostname (e.g. edge.comet.offhand.dev):"
write_env EDGE_HOSTNAME "$EDGE_HOSTNAME"
patch edge/wrangler.jsonc "s/edge\\.comet\\.zeron\\.sh/$EDGE_HOSTNAME/g" "$EDGE_HOSTNAME"
say ""
say "wrangler.jsonc also carries two leftover upstream path routes"
say "(comet.zeron.sh/install.sh and /releases/*). Your worker serves both"
say "paths on $EDGE_HOSTNAME directly, so:"
step "Open edge/wrangler.jsonc and DELETE the two comet.zeron.sh route lines."
pause "Deleted (or repointed) them?"
if grep -q 'zeron\.sh' edge/wrangler.jsonc; then
  warn "edge/wrangler.jsonc still mentions zeron.sh — finish that edit before deploying"
else
  say "${GREEN}✓${RESET} no zeron.sh routes left"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "R2 buckets"
say "Two buckets: blobs (attachments/backups) and releases (install tarballs)."
for b in comet-native-blobs comet-native-releases; do
  if ( cd edge && npx wrangler r2 bucket create "$b" >/dev/null 2>&1 ); then
    say "${GREEN}✓${RESET} created $b"
  else
    note "$b — already exists (fine) or creation failed; verify below"
  fi
done
( cd edge && npx wrangler r2 bucket list 2>/dev/null | head -20 ) || true
pause "Both buckets listed?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "First deploy — dev auth"
say "First deploy goes out with AUTH_MODE=dev because the smoke script"
say "refuses to run against workos auth (smoke.mjs:48). Flipping to workos"
say "is stage 7."
patch edge/wrangler.jsonc 's/"AUTH_MODE": "workos"/"AUTH_MODE": "dev"/' '"AUTH_MODE": "dev"'
if confirm "Deploy comet-native-edge to Cloudflare now?"; then
  ( cd edge && npx wrangler deploy )
  say ""
  step "Copy the URL wrangler just printed (workers.dev, or your hostname if"
  step "the zone is active)."
  ask EDGE_DEPLOY_URL "Deployed edge URL (https://…):"
  write_env EDGE_DEPLOY_URL "$EDGE_DEPLOY_URL"
else
  warn "skipped deploy — the remaining stages assume a deployed worker"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Smoke test (dev auth)"
say "Exercises rooms, tail, diff sidecar, device relay and the auth routes"
say "against the live worker."
( cd edge && node scripts/smoke.mjs "$EDGE_DEPLOY_URL" ) \
  && say "${GREEN}✓ smoke green${RESET}" \
  || { warn "smoke failed — fix before continuing (re-run: node edge/scripts/smoke.mjs $EDGE_DEPLOY_URL)"; pause; }

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "WorkOS environment"
say "The edge verifies WorkOS AuthKit JWTs (client id, public) and calls the"
say "WorkOS API for the /auth routes (API key, secret)."
open_url "https://dashboard.workos.com/"
step "Pick (or create) the environment your team will live in."
step "Left sidebar → 'API keys': copy the Client ID (starts client_...)."
ask WORKOS_CLIENT_ID "Paste the WorkOS Client ID:"
write_env WORKOS_CLIENT_ID "$WORKOS_CLIENT_ID"
patch edge/wrangler.jsonc "s/client_01KWD0EAKZKD50YCQJNYSRE4BY/$WORKOS_CLIENT_ID/" "$WORKOS_CLIENT_ID"
step "Same page: reveal + copy the API key (starts sk_...)."
ask_secret WORKOS_API_KEY "Paste the WorkOS API key:"
say "Storing it as a Worker secret (never lands in a file here):"
( cd edge && printf '%s' "$WORKOS_API_KEY" | npx wrangler secret put WORKOS_API_KEY ) \
  || warn "secret put failed — run by hand: cd edge && npx wrangler secret put WORKOS_API_KEY"
note "AuthKit redirect URIs (loopback + paste-code) are #52's checklist —"
note "the dashboard is already open when you get there."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Flip to production auth"
say "Dev bearers must die before a teammate touches this."
patch edge/wrangler.jsonc 's/"AUTH_MODE": "dev"/"AUTH_MODE": "workos"/' '"AUTH_MODE": "workos"'
if confirm "Redeploy with AUTH_MODE=workos?"; then
  ( cd edge && npx wrangler deploy )
  say "Checking /health reports workos:"
  curl -fsS "$EDGE_DEPLOY_URL/health" | grep -q '"auth":"workos"' \
    && say "${GREEN}✓ auth: workos${RESET}" \
    || warn "health did not report workos — inspect: curl $EDGE_DEPLOY_URL/health"
else
  warn "still on dev auth — do NOT leave it like this"
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "CI deploys — CLOUDFLARE_API_TOKEN"
say "deploy.yml deploys the edge on every push to main that touches edge/,"
say "once this repo secret exists."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Create Custom Token:"
step "  Account · Workers Scripts · Edit"
step "  Account · Workers R2 Storage · Edit"
step "  Zone · Workers Routes · Edit   (scope: your zone)"
step "Create, then copy the token — it is shown once."
ask_secret CF_API_TOKEN "Paste the Cloudflare API token:"
set_secret CLOUDFLARE_API_TOKEN "$CF_API_TOKEN"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Bake the new URLs into the clients"
say "Four hardcoded upstream URLs point clients at zeron.sh. Rewriting them"
say "to https://$EDGE_HOSTNAME:"
patch apps/comet/src/main.rs "s#https://edge\\.comet\\.zeron\\.sh#https://$EDGE_HOSTNAME#" "$EDGE_HOSTNAME"
patch apps/ios/Comet/App/AppModel.swift "s#https://edge\\.comet\\.zeron\\.sh#https://$EDGE_HOSTNAME#" "$EDGE_HOSTNAME"
patch apps/ios/Comet/Views/SignInView.swift "s#https://edge\\.comet\\.zeron\\.sh#https://$EDGE_HOSTNAME#" "$EDGE_HOSTNAME"
patch edge/src/install.sh "s#https://comet\\.zeron\\.sh#https://$EDGE_HOSTNAME#g" "$EDGE_HOSTNAME"
say ""
git diff --stat -- apps/comet/src/main.rs apps/ios edge/src/install.sh edge/wrangler.jsonc || true
say ""
note "Commit these through your normal flow — or tell the Claude session"
note "driving the board to pick them up and PR them."

finish
